db.schema.name: back_office

spring:
  main:
    banner-mode: 'off'
  # ===============================
  # = VIRTUAL THREADS
  # ===============================
  threads:
    virtual:
      enabled: true
  # ===============================
  # = DATASOURCE
  # ===============================
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
  # ===============================
  # = LIQUIBASE
  # ===============================
  liquibase:
    enabled: true
    default-schema: ${db.schema.name}
    change-log: classpath:db/changelog/db.changelog.yml
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        default_schema: ${db.schema.name}
# ===============================
# = ACTUATOR
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: '*'
# ===============================
# = SERVER
# ===============================
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /service
# ===============================
# = LOGGING
# ===============================
logging:
  level:
    root: info
    sql: info
    web: info
# ===============================
# = OpenApi
# ===============================
springdoc:
  swagger-ui:
    path: /swagger-ui.html
# ===============================
# = JWT
# ===============================
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_TTL} # ms
