spring:
  main:
    banner-mode: 'off'
  profiles:
    active: all
  datasource:
    url: jdbc:h2:mem:db
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
  # ===============================
  # = H2 Settings
  # ===============================
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
# ===============================
# = WEB
# ===============================
server:
  port: 8080
# ===============================
# = LOGGING
# ===============================
logging:
  level:
    root: info
    sql:  info
    web:  info