spring:
  application:
    name: ${APP_NAME}
  # ===============================
  # = VIRTUAL THREADS
  # ===============================
  threads:
    virtual:
      enabled: true
  # ===============================
  # = DATASOURCE
  # ===============================
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
  # ===============================
  # = LIQUIBASE
  # ===============================
  liquibase:
    enabled: true
    default-schema: ${DB_SCHEMA}
    change-log: classpath:db/changelog/db.changelog.yml
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: ${DB_SCHEMA}
# ===============================
# = ACTUATOR
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: '*'
# ===============================
# = SERVER
# ===============================
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /service
# ===============================
# = LOGGING
# ===============================
logging:
  level:
    root: info
    sql: info
    web: info
# ===============================
# = JWT
# ===============================
jwt:
  secret: ${JWT_SECRET}
  expiration-seconds: ${JWT_TTL_SECONDS:3600}
