client:
  base-url: http://localhost:8080/service
  path: /api
  apache-http-client:
    connection-timeout: 10s
    socket-timeout: 60s
    pooling:
      max-total: 200
      default-max-per-route: 100
    retry:
      count: 3
      interval: 10
