name: Java CI with Gradle

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker JVM Image
        run: docker build --no-cache --file ./jvm.Dockerfile .

      - name: Build Docker Native Image
        run: docker build --file ./native.Dockerfile .
